cargo: fix version of proc-macro2
It turns out that you cannot publish a package on crates.io if it has
a wildcard dependency:

  error: api errors: wildcard (`*`) dependency constraints are not
  allowed on crates.io.